CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "role" varchar,
  "phone" varchar,
  "address" text,
  "business_details" text,
  "is_active" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "domains" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "active" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "domain_configurations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain_id" int,
  "banner_url" varchar,
  "service_types" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "services" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provider_id" int,
  "category_id" int,
  "title" varchar,
  "description" text,
  "image_url" varchar,
  "price" decimal,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "service_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int,
  "image_url" varchar,
  "created_at" timestamp
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int,
  "user_id" int,
  "status" varchar,
  "total_price" decimal,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "payment_type" varchar,
  "payment_status" varchar,
  "transaction_id" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "apartment_number" varchar,
  "building_name" varchar,
  "street_name" varchar,
  "additional_details" text,
  "is_default" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int,
  "cart_id" int,
  "quantity" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "coupons" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "discount_percentage" int,
  "valid_from" date,
  "valid_to" date,
  "usage_limit" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "service_id" int,
  "created_at" timestamp
);

CREATE TABLE "complaints" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "subject" varchar,
  "message" text,
  "status" varchar,
  "response" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "banners" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_url" varchar,
  "title" varchar,
  "is_active" boolean,
  "position" varchar,
  "start_date" date,
  "end_date" date,
  "created_at" timestamp
);

CREATE TABLE "terms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "faqs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question" text,
  "answer" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "ratings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int,
  "user_id" int,
  "rating" int,
  "feedback" text,
  "created_at" timestamp
);

CREATE TABLE "loyalty_rules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "required_orders" int,
  "granted_points" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "loyalty_rewards" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reward_name" varchar,
  "required_points" int,
  "reward_description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "user_loyalty_points" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "completed_orders" int,
  "total_points" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "user_reward_claims" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "reward_id" int,
  "claimed_at" timestamp
);

CREATE TABLE "provider_loyalty_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provider_id" int,
  "total_orders" int,
  "total_points_granted" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "settings" (
  "id" PK,
  "site_name" varchar,
  "site_description" varchar,
  "logo_url" varchar,
  "favicon_url" varchar,
  "currency" varchar,
  "support_email" varchar,
  "support_phone" varchar,
  "booking_terms_url" varchar,
  "privacy_policy_url" varchar,
  "social_links" JSON,
  "header_scripts" varchar,
  "footer_scripts" varchar,
  "smtp_config" JSON
);

ALTER TABLE "domain_configurations" ADD FOREIGN KEY ("domain_id") REFERENCES "domains" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("provider_id") REFERENCES "users" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "service_images" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "complaints" ADD FOREIGN KEY ("user_id") REFERENCES "services" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_loyalty_points" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_reward_claims" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_reward_claims" ADD FOREIGN KEY ("reward_id") REFERENCES "loyalty_rewards" ("id");

ALTER TABLE "provider_loyalty_stats" ADD FOREIGN KEY ("provider_id") REFERENCES "users" ("id");
